name: "iOS Build"

on:
  workflow_call:
    inputs:
      publish:
        required: false
        type: boolean
        description: Publish to Appcenter
      track:
        required: true
        type: string
    secrets:
      IOS_P12_BASE64:
        required: true
      IOS_MOBILEPROVISION_BASE64:
        required: true
      IOS_TEAM_ID:
        required: true
      IOS_CERTIFICATE_PASSWORD:
        required: true
      APPLEID_USERNAME:
        required: true
      APPLEID_PASSWORD:
        required: true

jobs:
  build-ios:
    runs-on: macos-12 #Monterey
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 18.1
        uses: actions/setup-node@v3
        with:
          node-version: 18.1

      - name: Install Node modules
        run: yarn install

      - name: Build ios capacitor
        run:  |
          if [ "${{ inputs.track }}" = "production" ]; then
            echo "Building for production..."
            yarn build-ios:prod
          elif [ "${{ inputs.track }}" = "alpha" ]]; then
            echo "Building for alpha..."
            yarn build-ios:dev
          else
            echo "Building for default track..."
            yarn build-ios:dev
          fi

      - name: Install pod dependencies
        run: cd ios && cd App && pod install && cd .. && cd ..

      - name: Syncronize Capacitor
        run: npx cap sync ios

      - name: Build iOS (Release)
        uses: yukiarrr/ios-build-action@v1.11.2
        with:
          project-path: ios/App/App.xcodeproj
          p12-base64: ${{ secrets.IOS_P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.IOS_MOBILEPROVISION_BASE64 }}
          code-signing-identity: "Apple Distribution"
          team-id: ${{ secrets.IOS_TEAM_ID }}
          workspace-path: ios/App/App.xcworkspace
          output-path: "Timely.ipa"
          certificate-password: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
          bundle-identifier: "cicd.com.irricontrol"

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: "Timely.ipa"
          path: "Timely.ipa"

      - name: Upload to App Store Connect
        env:
          APPLEID_USERNAME: ${{ secrets.APPLEID_USERNAME }}
          APPLEID_PASSWORD: ${{ secrets.APPLEID_PASSWORD }}
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          xcrun altool --upload-app \
            -t ios \
            -f Timely.ipa \
            -u $APPLEID_USERNAME \
            -p $APPLEID_PASSWORD

      - name: Clean up keychain and provisioning profile
        if: ${{ always() }}
        run: |
          security delete-keychain $RUNNER_TEMP/app-signing.keychain-db
          rm ~/Library/MobileDevice/Provisioning\ Profiles/*.mobileprovision
