name: Pull Request into Master, Develop and Preprod

on:
  pull_request:
    branches:
      - "development"
 
jobs:
  #First job
  install-and-test:
    runs-on: ubuntu-latest
    outputs:
      track: ${{ steps.set_track.outputs.track }}  # Define o output no nível do job
  
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18.1
        uses: actions/setup-node@v3
        with:
          node-version: 18.1

      - name: Install Node modules
        run: yarn install
        
      - name: Set track based on branch or input
        id: set_track
        run: |
          if [[ ${{ github.base_ref }} == 'main' ]]; then
            echo "::set-output name=track::production"
          else
            echo "::set-output name=track::alpha"
          fi


  # Second Job
  build-android:
    needs: install-and-test
    uses: ./.github/workflows/build-android.yml
    secrets: inherit
    with:
      publish: true
      track: ${{ needs.install-and-test.outputs.track }} 
  build-ios:
    needs: install-and-test
    uses: ./.github/workflows/build-ios.yml
    secrets: inherit
    with:
      publish: true
      track: ${{ needs.install-and-test.outputs.track }} 
