name: Pull Request into Master, Develop and Preprod

on:
  pull_request:
    branches:
      - "development"

jobs:
  #First job
  install-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18.1
        uses: actions/setup-node@v3
        with:
          node-version: 18.1
          cache: "yarn"

      - name: Install Node modules
        run: yarn

  # Second Job
  build-android:
    needs: install-and-test
    uses: ./.github/workflows/build-android.yml
    secrets: inherit

  # Third Job
  #build-ios:
  #  needs: install-and-test
  #  uses: ./.github/workflows/build-ios.yml
  #  secrets: inherit
