name: Pull Request into Master, Develop and Preprod

on:
  pull_request:
    branches:
      - "development"
  workflow_dispatch:
    outputs:
      track: ${{ steps.set_track.outputs.track }}  # Definir o output aqui para ser usado por outros jobs

jobs:
  #First job
  install-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18.1
        uses: actions/setup-node@v3
        with:
          node-version: 18.1

      - name: Install Node modules
        run: yarn install
        
      - name: Set track based on branch or input
        id: set_track
        run: |
          if [[ "${{ github.event.inputs.track }}" != '' ]]; then
            echo "Using manual input for track"
            TRACK="${{ github.event.inputs.track }}"
          elif [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            TRACK="production"
          elif [[ $GITHUB_REF != 'refs/heads/main' ]]; then
            TRACK="alpha"
          fi
          echo "::set-output name=track::$TRACK"


  # Second Job
  build-android:
    needs: install-and-test
    uses: ./.github/workflows/build-android.yml
    secrets: inherit
    with:
      publish: true
      track: ${{ needs.install-and-test.outputs.track }} 
  # Third Job
  #build-ios:
  #  needs: install-and-test
  #  uses: ./.github/workflows/build-ios.yml
  #  secrets: inherit
